.\" Manpage for liat 
.\" Contact steve@stevenlamers.com to correct errors or typos.
.TH man 1 "03 May 2019" "Beta 1.0" "liat man page"
.SH NAME
liat \- List It At the Top 
.SH SYNOPSIS
liat [FILE]
.SH DESCRIPTION
liat is an ncurses application that reads lines from  stdin and prints the lines to the screen. 
.SH OPTIONS
There are no options
.SH SEE ALSO
tail
.SH BUGS
No known bugs. The maximum line length attempted to read is 400 chars, including the newline and null terminator. The maximun number of lines available is 100. 
.SH AUTHOR
Steven Lamers (steve@stevenlamers.com)
.SH COPYRIGHT
Copyright   ©   2025   Steven G. Lamers - All Rights Reserved.

