.\" Manpage for liat 
.\" Contact steve@stevenlamers.com to correct errors or typos.
.TH man 1 "03 May 2019" "Beta 1.0" "liat man page"
.SH NAME
liat \- List It At the Top 
.SH SYNOPSIS
liat [FILE]
.SH DESCRIPTION
liat is an ncurses application that reads lines from FILE or stdin and prints the lines to the screen. The FILE is monitored and as the FILE grows the appended data is written to the screen. The top line of the screen is updated and the rest of the screen is scrolled down. The bottom line is lost each time the screen is full and the top line is updated.
.SH OPTIONS
liat takes an optional FILE filename. If no FILE is given liat reads lines from stdin.
.SH SEE ALSO
tail
.SH BUGS
No known bugs. The maximun line length attempted to read is 1024 chars, including the newline and null terminator. The maximun number of lines available is 200. 
.SH AUTHOR
Steven Lamers (steve@stevenlamers.com)
.SH COPYRIGHT
Copyright   ©   2019   Steven G. Lamers

